{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.basicAuth }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-kuma.fullname" . }}-metrics-basic-auth
  namespace: {{ default .Release.Namespace .Values.serviceMonitor.namespace }}
type: kubernetes.io/basic-auth
stringData:
{{- range $key, $value := .Values.serviceMonitor.basicAuth }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
