apiVersion: v2
appVersion: 1.23.13
description: A self-hosted Monitoring tool like "Uptime-Robot".
home: https://github.com/dirsigler/uptime-kuma-helm
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
maintainers:
- email: dennis@irsigler.dev
  name: dirsigler
name: uptime-kuma
sources:
- https://github.com/louislam/uptime-kuma
type: application
version: 2.20.0
